eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost


microservice:
  microservicio-producto:
    endpoints:
      endpoint:
        uri: http://MICROSERVICIO-PRODUCTO/productos
  microservicio-calcular-nuevos-precios:
    endpoints:
      endpoint:
        uri: http://MICROSERVICIO-CALCULAR-NUEVOS-PRECIOS/calcular-nuevos-precios
