server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
      routes:
        - id: producto-service
          uri: lb://producto-service
          predicates:
            - Path=/productos/**
        - id: calcular-nuevos-precios-service
          uri: lb://calcular-nuevos-precios-service
          predicates:
            - Path=/calcular-nuevos-precios/**
